### ISSUE TITLE
cannot import name 'amp' from 'torch.cuda' 

### ISSUE THREAD

**Issue by Shannia-Shan** [HXLH50K/U-Net-Transformer#4]
Hi! Thank you for sharing the wonderful job.

When I ran the train.py, I got the errors like the following:

Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from torch.cuda import amp
ImportError: cannot import name 'amp' from 'torch.cuda' (/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py)

I searched a lot and tried to find the resolution. It seems there is an issue with the version compatibility. What are your PyTorch version and CUDA version? 
Thanks a lot!

**Comment by Shannia-Shan** [comment]
> Hi! Thank you for sharing the wonderful job.
> 
> When I ran the train.py, I got the errors like the following:
> 
> Traceback (most recent call last):
> File "train.py", line 12, in
> from torch.cuda import amp
> ImportError: cannot import name 'amp' from 'torch.cuda' (/usr/local/lib/python3.7/dist-packages/torch/cuda/**init**.py)
> 
> I searched a lot and tried to find the resolution. It seems there is an issue with the version compatibility. What are your PyTorch version and CUDA version?
> Thanks a lot!

The issue was resolved!
